//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSRecycleViewPlugin\src\main\java\com\ashera\recycleview\FixedGridViewManager.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "FixedGridViewManager.h"
#include "J2ObjC_source.h"
#include "RecyclerView.h"
#include "View.h"
#include "ViewGroup.h"
#include "java/lang/Integer.h"




#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface ASFixedGridViewManager () {
 @public
  int32_t rows_;
  int32_t cols_;
}

@end

@implementation ASFixedGridViewManager

- (instancetype)initWithInt:(int32_t)rows
                    withInt:(int32_t)cols {
  ASFixedGridViewManager_initWithInt_withInt_(self, rows, cols);
  return self;
}

- (ADXRecyclerView_LayoutParams *)generateDefaultLayoutParams {
  return new_ADXRecyclerView_LayoutParams_initWithInt_withInt_(ADViewGroup_LayoutParams_WRAP_CONTENT, ADViewGroup_LayoutParams_WRAP_CONTENT);
}

- (void)onLayoutChildrenWithADXRecyclerView_Recycler:(ADXRecyclerView_Recycler *)recycler
                           withADXRecyclerView_State:(ADXRecyclerView_State *)state {
  [self detachAndScrapAttachedViewsWithADXRecyclerView_Recycler:recycler];
  if ([self getItemCount] == 0 || rows_ == 0 || cols_ == 0) {
    return;
  }
  int32_t parentWidth = [self getWidth];
  int32_t parentHeight = [self getHeight];
  int32_t cellWidth = JreIntDiv(parentWidth, cols_);
  int32_t cellHeight = JreIntDiv(parentHeight, rows_);
  for (int32_t i = 0; i < [self getItemCount]; i++) {
    ADView *view = [((ADXRecyclerView_Recycler *) nil_chk(recycler)) getViewForPositionWithInt:i];
    [self addViewWithADView:view];
    int32_t widthSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(cellWidth, ADView_MeasureSpec_EXACTLY);
    int32_t heightSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(cellHeight, ADView_MeasureSpec_EXACTLY);
    [((ADView *) nil_chk(view)) measureWithInt:widthSpec withInt:heightSpec];
    int32_t row = JreIntDiv(i, cols_);
    int32_t col = JreIntMod(i, cols_);
    int32_t left = col * cellWidth;
    int32_t top = row * cellHeight;
    int32_t right = (col == cols_ - 1) ? parentWidth : left + cellWidth;
    int32_t bottom = (row == rows_ - 1) ? parentHeight : top + cellHeight;
    [self layoutDecoratedWithADView:view withInt:left withInt:top withInt:right withInt:bottom];
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LADXRecyclerView_LayoutParams;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 1, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithInt:withInt:);
  methods[1].selector = @selector(generateDefaultLayoutParams);
  methods[2].selector = @selector(onLayoutChildrenWithADXRecyclerView_Recycler:withADXRecyclerView_State:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "rows_", "I", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "cols_", "I", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "II", "onLayoutChildren", "LADXRecyclerView_Recycler;LADXRecyclerView_State;" };
  static const J2ObjcClassInfo _ASFixedGridViewManager = { "FixedGridViewManager", "com.ashera.recycleview", ptrTable, methods, fields, 7, 0x1, 3, 2, -1, -1, -1, -1, -1 };
  return &_ASFixedGridViewManager;
}

@end

void ASFixedGridViewManager_initWithInt_withInt_(ASFixedGridViewManager *self, int32_t rows, int32_t cols) {
  ADXRecyclerView_LayoutManager_init(self);
  self->rows_ = rows;
  self->cols_ = cols;
}

ASFixedGridViewManager *new_ASFixedGridViewManager_initWithInt_withInt_(int32_t rows, int32_t cols) {
  J2OBJC_NEW_IMPL(ASFixedGridViewManager, initWithInt_withInt_, rows, cols)
}

ASFixedGridViewManager *create_ASFixedGridViewManager_initWithInt_withInt_(int32_t rows, int32_t cols) {
  J2OBJC_CREATE_IMPL(ASFixedGridViewManager, initWithInt_withInt_, rows, cols)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASFixedGridViewManager)

J2OBJC_NAME_MAPPING(ASFixedGridViewManager, "com.ashera.recycleview", "AS")
