//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSRecycleViewPlugin\src\main\java\com\ashera\recycleview\FixedGridViewManager.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_FixedGridViewManager")
#ifdef RESTRICT_FixedGridViewManager
#define INCLUDE_ALL_FixedGridViewManager 0
#else
#define INCLUDE_ALL_FixedGridViewManager 1
#endif
#undef RESTRICT_FixedGridViewManager

#if !defined (ASFixedGridViewManager_) && (INCLUDE_ALL_FixedGridViewManager || defined(INCLUDE_ASFixedGridViewManager))
#define ASFixedGridViewManager_

#define RESTRICT_RecyclerView 1
#define INCLUDE_ADXRecyclerView_LayoutManager 1
#include "RecyclerView.h"

@class ADXRecyclerView_LayoutParams;
@class ADXRecyclerView_Recycler;
@class ADXRecyclerView_State;
@class JavaLangInteger;

@interface ASFixedGridViewManager : ADXRecyclerView_LayoutManager

#pragma mark Public

- (instancetype)initWithInt:(int32_t)rows
                    withInt:(int32_t)cols;

- (ADXRecyclerView_LayoutParams *)generateDefaultLayoutParams;

- (void)onLayoutChildrenWithADXRecyclerView_Recycler:(ADXRecyclerView_Recycler *)recycler
                           withADXRecyclerView_State:(ADXRecyclerView_State *)state;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASFixedGridViewManager)

FOUNDATION_EXPORT void ASFixedGridViewManager_initWithInt_withInt_(ASFixedGridViewManager *self, int32_t rows, int32_t cols);

FOUNDATION_EXPORT ASFixedGridViewManager *new_ASFixedGridViewManager_initWithInt_withInt_(int32_t rows, int32_t cols) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASFixedGridViewManager *create_ASFixedGridViewManager_initWithInt_withInt_(int32_t rows, int32_t cols);

J2OBJC_TYPE_LITERAL_HEADER(ASFixedGridViewManager)

@compatibility_alias ComAsheraRecycleviewFixedGridViewManager ASFixedGridViewManager;


#endif

#pragma pop_macro("INCLUDE_ALL_FixedGridViewManager")
