//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSRecycleViewPlugin\src\main\java\com\ashera\recycleview\GenericTouchHelperSimpleCallback.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "GenericTouchHelperSimpleCallback.h"
#include "ILifeCycleDecorator.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IWidget.h"
#include "ItemActionHandler.h"
#include "ItemTouchHelper.h"
#include "J2ObjC_source.h"
#include "ModelExpressionParser.h"
#include "MyItemTouchHelper.h"
#include "RecyclerView.h"
#include "View.h"
#include "java/lang/Boolean.h"
#include "java/lang/Integer.h"
#include "java/util/List.h"
#include "java/util/Map.h"
#include "java/util/Set.h"


@class NSString;


#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface ASGenericTouchHelperSimpleCallback () {
 @public
  id<ASMyItemTouchHelper_MyCallback> swipeListener_;
  id<ASMyItemTouchHelper_MyCallback> onMoveListener_;
  id<ASMyItemTouchHelper_MyCallback> onMovedListener_;
  id<ASMyItemTouchHelper_MyCallback> onSelectedChangedListener_;
  bool deleteOnSwipe_;
  NSString *swipeSwapMode_;
  ADXRecyclerView_Adapter *adapter_;
  int32_t fromPosition_;
  int32_t toPosition_;
  ADXRecyclerView_ViewHolder *currentTarget_;
  NSString *dragmode_;
  NSString *dragStartMode_;
  NSString *swapMode_;
  NSString *selectHighlightAttributes_;
  NSString *resetHighlightAttributes_;
}

- (void)applyStyleWithADView:(ADView *)itemView
                withNSString:(NSString *)cssExpression;

- (void)resetViewWithADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder;

- (void)onItemMoveWithInt:(int32_t)fromPosition
                  withInt:(int32_t)toPosition;

@end

J2OBJC_FIELD_SETTER(ASGenericTouchHelperSimpleCallback, swipeListener_, id<ASMyItemTouchHelper_MyCallback>)
J2OBJC_FIELD_SETTER(ASGenericTouchHelperSimpleCallback, onMoveListener_, id<ASMyItemTouchHelper_MyCallback>)
J2OBJC_FIELD_SETTER(ASGenericTouchHelperSimpleCallback, onMovedListener_, id<ASMyItemTouchHelper_MyCallback>)
J2OBJC_FIELD_SETTER(ASGenericTouchHelperSimpleCallback, onSelectedChangedListener_, id<ASMyItemTouchHelper_MyCallback>)
J2OBJC_FIELD_SETTER(ASGenericTouchHelperSimpleCallback, swipeSwapMode_, NSString *)
J2OBJC_FIELD_SETTER(ASGenericTouchHelperSimpleCallback, adapter_, ADXRecyclerView_Adapter *)
J2OBJC_FIELD_SETTER(ASGenericTouchHelperSimpleCallback, currentTarget_, ADXRecyclerView_ViewHolder *)
J2OBJC_FIELD_SETTER(ASGenericTouchHelperSimpleCallback, dragmode_, NSString *)
J2OBJC_FIELD_SETTER(ASGenericTouchHelperSimpleCallback, dragStartMode_, NSString *)
J2OBJC_FIELD_SETTER(ASGenericTouchHelperSimpleCallback, swapMode_, NSString *)
J2OBJC_FIELD_SETTER(ASGenericTouchHelperSimpleCallback, selectHighlightAttributes_, NSString *)
J2OBJC_FIELD_SETTER(ASGenericTouchHelperSimpleCallback, resetHighlightAttributes_, NSString *)

__attribute__((unused)) static void ASGenericTouchHelperSimpleCallback_applyStyleWithADView_withNSString_(ASGenericTouchHelperSimpleCallback *self, ADView *itemView, NSString *cssExpression);

__attribute__((unused)) static void ASGenericTouchHelperSimpleCallback_resetViewWithADXRecyclerView_ViewHolder_(ASGenericTouchHelperSimpleCallback *self, ADXRecyclerView_ViewHolder *viewHolder);

__attribute__((unused)) static void ASGenericTouchHelperSimpleCallback_onItemMoveWithInt_withInt_(ASGenericTouchHelperSimpleCallback *self, int32_t fromPosition, int32_t toPosition);

@implementation ASGenericTouchHelperSimpleCallback

- (NSString *)getSelectHighlightAttributes {
  return selectHighlightAttributes_;
}

- (void)setSelectHighlightAttributesWithNSString:(NSString *)selectHighlightAttributes {
  self->selectHighlightAttributes_ = selectHighlightAttributes;
}

- (NSString *)getResetHighlightAttributes {
  return resetHighlightAttributes_;
}

- (NSString *)getDragStartMode {
  return dragStartMode_;
}

- (void)setDragStartModeWithNSString:(NSString *)dragStartMode {
  self->dragStartMode_ = dragStartMode;
}

- (void)setResetHighlightAttributesWithNSString:(NSString *)resetHighlightAttributes {
  self->resetHighlightAttributes_ = resetHighlightAttributes;
}

- (NSString *)getSwapMode {
  return swapMode_;
}

- (void)setSwapModeWithNSString:(NSString *)swapMode {
  self->swapMode_ = swapMode;
}

- (NSString *)getSwipeSwapMode {
  return swipeSwapMode_;
}

- (void)setSwipeSwapModeWithNSString:(NSString *)swipeSwapMode {
  self->swipeSwapMode_ = swipeSwapMode;
}

- (bool)isDeleteOnSwipe {
  return deleteOnSwipe_;
}

- (void)setDeleteOnSwipeWithBoolean:(bool)deleteOnSwipe {
  self->deleteOnSwipe_ = deleteOnSwipe;
}

- (id<ASMyItemTouchHelper_MyCallback>)getSwipeListener {
  return swipeListener_;
}

- (void)setSwipeListenerWithASMyItemTouchHelper_MyCallback:(id<ASMyItemTouchHelper_MyCallback>)swipeListener {
  self->swipeListener_ = swipeListener;
}

- (id<ASMyItemTouchHelper_MyCallback>)getOnMoveListener {
  return onMoveListener_;
}

- (void)setOnMoveListenerWithASMyItemTouchHelper_MyCallback:(id<ASMyItemTouchHelper_MyCallback>)onMoveListener {
  self->onMoveListener_ = onMoveListener;
}

- (id<ASMyItemTouchHelper_MyCallback>)getOnMovedListener {
  return onMovedListener_;
}

- (void)setOnMovedListenerWithASMyItemTouchHelper_MyCallback:(id<ASMyItemTouchHelper_MyCallback>)onMovedListener {
  self->onMovedListener_ = onMovedListener;
}

- (id<ASMyItemTouchHelper_MyCallback>)getOnSelectedChangedListener {
  return onSelectedChangedListener_;
}

- (void)setOnSelectedChangedListenerWithASMyItemTouchHelper_MyCallback:(id<ASMyItemTouchHelper_MyCallback>)onSelectedChangedListener {
  self->onSelectedChangedListener_ = onSelectedChangedListener;
}

- (instancetype)initWithADXRecyclerView_Adapter:(ADXRecyclerView_Adapter *)adapter
                                        withInt:(int32_t)dragDirs
                                        withInt:(int32_t)swipeDirs {
  ASGenericTouchHelperSimpleCallback_initWithADXRecyclerView_Adapter_withInt_withInt_(self, adapter, dragDirs, swipeDirs);
  return self;
}

- (ADXRecyclerView_ViewHolder *)chooseDropTargetWithADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)selected
                                                              withJavaUtilList:(id<JavaUtilList>)dropTargets
                                                                       withInt:(int32_t)curX
                                                                       withInt:(int32_t)curY {
  ADXRecyclerView_ViewHolder *target = [super chooseDropTargetWithADXRecyclerView_ViewHolder:selected withJavaUtilList:dropTargets withInt:curX withInt:curY];
  if (currentTarget_ != nil && !JreObjectEqualsEquals(currentTarget_, target)) {
    ASGenericTouchHelperSimpleCallback_resetViewWithADXRecyclerView_ViewHolder_(self, currentTarget_);
  }
  if (target != nil) {
    if (!JreObjectEqualsEquals(currentTarget_, target)) {
      [self selectViewWithADXRecyclerView_ViewHolder:target];
    }
  }
  else {
    toPosition_ = -1;
  }
  currentTarget_ = target;
  return target;
}

- (void)selectViewWithADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder {
  ADView *itemView = ((ADXRecyclerView_ViewHolder *) nil_chk(viewHolder))->itemView_;
  if ([ASILifeCycleDecorator_class_() isInstance:itemView]) {
    if (selectHighlightAttributes_ != nil) {
      ASGenericTouchHelperSimpleCallback_applyStyleWithADView_withNSString_(self, itemView, selectHighlightAttributes_);
    }
  }
}

- (void)applyStyleWithADView:(ADView *)itemView
                withNSString:(NSString *)cssExpression {
  ASGenericTouchHelperSimpleCallback_applyStyleWithADView_withNSString_(self, itemView, cssExpression);
}

- (void)resetViewWithADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder {
  ASGenericTouchHelperSimpleCallback_resetViewWithADXRecyclerView_ViewHolder_(self, viewHolder);
}

- (void)onSelectedChangedWithADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder
                                                withInt:(int32_t)actionState {
  [super onSelectedChangedWithADXRecyclerView_ViewHolder:viewHolder withInt:actionState];
  if (actionState == ADXItemTouchHelper_ACTION_STATE_DRAG && viewHolder != nil) {
    [self selectViewWithADXRecyclerView_ViewHolder:viewHolder];
  }
  if (onSelectedChangedListener_ != nil) {
    [onSelectedChangedListener_ onSelectedChangedWithADXRecyclerView_ViewHolder:viewHolder withInt:actionState];
  }
}

- (bool)onMoveWithADXRecyclerView:(ADXRecyclerView *)recyclerView
   withADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder
   withADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)target {
  if ([((ADXRecyclerView_ViewHolder *) nil_chk(viewHolder)) getItemViewType] != [((ADXRecyclerView_ViewHolder *) nil_chk(target)) getItemViewType]) {
    return false;
  }
  fromPosition_ = [viewHolder getAdapterPosition];
  toPosition_ = [target getAdapterPosition];
  if (dragmode_ != nil && [dragmode_ isEqual:@"swaponhighlight"]) {
    ASGenericTouchHelperSimpleCallback_onItemMoveWithInt_withInt_(self, fromPosition_, toPosition_);
    if (onMovedListener_ != nil) {
      [onMovedListener_ onMovedWithADXRecyclerView:recyclerView withInt:fromPosition_ withInt:toPosition_];
    }
  }
  if (onMoveListener_ != nil) {
    [onMoveListener_ onMoveWithADXRecyclerView:recyclerView withADXRecyclerView_ViewHolder:viewHolder withADXRecyclerView_ViewHolder:target];
  }
  return true;
}

- (void)onSwipedWithADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder
                                       withInt:(int32_t)direction {
  if (deleteOnSwipe_) {
    int32_t position = [((ADXRecyclerView_ViewHolder *) nil_chk(viewHolder)) getAdapterPosition];
    if ([ASItemActionHandler_class_() isInstance:adapter_]) {
      [((id<ASItemActionHandler>) nil_chk(((id<ASItemActionHandler>) cast_check(adapter_, ASItemActionHandler_class_())))) onItemRemoveWithInt:position withNSString:swipeSwapMode_];
    }
  }
  if (swipeListener_ != nil) {
    [swipeListener_ onSwipedWithADXRecyclerView_ViewHolder:viewHolder withInt:direction];
  }
}

- (bool)isLongPressDragEnabled {
  return dragStartMode_ != nil && [dragStartMode_ isEqual:@"longpress"];
}

- (bool)isDownPressDragEnabled {
  return dragStartMode_ != nil && [dragStartMode_ isEqual:@"onclick"];
}

- (void)clearViewWithADXRecyclerView:(ADXRecyclerView *)recyclerView
      withADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder {
  [super clearViewWithADXRecyclerView:recyclerView withADXRecyclerView_ViewHolder:viewHolder];
  ASGenericTouchHelperSimpleCallback_resetViewWithADXRecyclerView_ViewHolder_(self, viewHolder);
  if (currentTarget_ != nil) {
    ASGenericTouchHelperSimpleCallback_resetViewWithADXRecyclerView_ViewHolder_(self, currentTarget_);
  }
  if (fromPosition_ != -1 && toPosition_ != -1 && fromPosition_ != toPosition_) {
    if (dragmode_ != nil && [dragmode_ isEqual:@"swapwhendropped"]) {
      ASGenericTouchHelperSimpleCallback_onItemMoveWithInt_withInt_(self, fromPosition_, toPosition_);
      if (onMovedListener_ != nil) {
        [onMovedListener_ onMovedWithADXRecyclerView:recyclerView withInt:fromPosition_ withInt:toPosition_];
      }
    }
  }
  currentTarget_ = nil;
  fromPosition_ = -1;
  toPosition_ = -1;
}

- (void)onItemMoveWithInt:(int32_t)fromPosition
                  withInt:(int32_t)toPosition {
  ASGenericTouchHelperSimpleCallback_onItemMoveWithInt_withInt_(self, fromPosition, toPosition);
}

- (NSString *)getDragmode {
  return dragmode_;
}

- (void)setDragmodeWithNSString:(NSString *)dragmode {
  self->dragmode_ = dragmode;
}

- (int32_t)getMovementFlagsWithADXRecyclerView:(ADXRecyclerView *)recyclerView
                withADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder {
  if ([ASItemActionHandler_class_() isInstance:adapter_]) {
    if (![((id<ASItemActionHandler>) nil_chk(((id<ASItemActionHandler>) cast_check(adapter_, ASItemActionHandler_class_())))) isDragEnabledWithADXRecyclerView_ViewHolder:viewHolder]) {
      return ADXItemTouchHelper_Callback_makeMovementFlagsWithInt_withInt_(0, 0);
    }
  }
  return [super getMovementFlagsWithADXRecyclerView:recyclerView withADXRecyclerView_ViewHolder:viewHolder];
}

- (int32_t)getSwipeDirsWithADXRecyclerView:(ADXRecyclerView *)recyclerView
            withADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder {
  if ([ASItemActionHandler_class_() isInstance:adapter_]) {
    int32_t swipeDirs = [((id<ASItemActionHandler>) nil_chk(((id<ASItemActionHandler>) cast_check(adapter_, ASItemActionHandler_class_())))) getSwipeDirsWithADXRecyclerView_ViewHolder:viewHolder];
    if (swipeDirs != -1) {
      return swipeDirs;
    }
  }
  return [super getSwipeDirsWithADXRecyclerView:recyclerView withADXRecyclerView_ViewHolder:viewHolder];
}

- (int32_t)getDragDirsWithADXRecyclerView:(ADXRecyclerView *)recyclerView
           withADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder {
  if ([ASItemActionHandler_class_() isInstance:adapter_]) {
    int32_t dragDirs = [((id<ASItemActionHandler>) nil_chk(((id<ASItemActionHandler>) cast_check(adapter_, ASItemActionHandler_class_())))) getDragDirsWithADXRecyclerView_ViewHolder:viewHolder];
    if (dragDirs != -1) {
      return dragDirs;
    }
  }
  return [super getDragDirsWithADXRecyclerView:recyclerView withADXRecyclerView_ViewHolder:viewHolder];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 5, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "LASMyItemTouchHelper_MyCallback;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 8, 9, -1, -1, -1, -1 },
    { NULL, "LASMyItemTouchHelper_MyCallback;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 9, -1, -1, -1, -1 },
    { NULL, "LASMyItemTouchHelper_MyCallback;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 11, 9, -1, -1, -1, -1 },
    { NULL, "LASMyItemTouchHelper_MyCallback;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 12, 9, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 13, -1, 14, -1, -1 },
    { NULL, "LADXRecyclerView_ViewHolder;", 0x1, 15, 16, -1, 17, -1, -1 },
    { NULL, "V", 0x1, 18, 19, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 20, 21, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 22, 19, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 23, 24, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 25, 26, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 27, 24, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 28, 29, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 30, 31, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 32, 1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 33, 29, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 34, 29, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 35, 29, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getSelectHighlightAttributes);
  methods[1].selector = @selector(setSelectHighlightAttributesWithNSString:);
  methods[2].selector = @selector(getResetHighlightAttributes);
  methods[3].selector = @selector(getDragStartMode);
  methods[4].selector = @selector(setDragStartModeWithNSString:);
  methods[5].selector = @selector(setResetHighlightAttributesWithNSString:);
  methods[6].selector = @selector(getSwapMode);
  methods[7].selector = @selector(setSwapModeWithNSString:);
  methods[8].selector = @selector(getSwipeSwapMode);
  methods[9].selector = @selector(setSwipeSwapModeWithNSString:);
  methods[10].selector = @selector(isDeleteOnSwipe);
  methods[11].selector = @selector(setDeleteOnSwipeWithBoolean:);
  methods[12].selector = @selector(getSwipeListener);
  methods[13].selector = @selector(setSwipeListenerWithASMyItemTouchHelper_MyCallback:);
  methods[14].selector = @selector(getOnMoveListener);
  methods[15].selector = @selector(setOnMoveListenerWithASMyItemTouchHelper_MyCallback:);
  methods[16].selector = @selector(getOnMovedListener);
  methods[17].selector = @selector(setOnMovedListenerWithASMyItemTouchHelper_MyCallback:);
  methods[18].selector = @selector(getOnSelectedChangedListener);
  methods[19].selector = @selector(setOnSelectedChangedListenerWithASMyItemTouchHelper_MyCallback:);
  methods[20].selector = @selector(initWithADXRecyclerView_Adapter:withInt:withInt:);
  methods[21].selector = @selector(chooseDropTargetWithADXRecyclerView_ViewHolder:withJavaUtilList:withInt:withInt:);
  methods[22].selector = @selector(selectViewWithADXRecyclerView_ViewHolder:);
  methods[23].selector = @selector(applyStyleWithADView:withNSString:);
  methods[24].selector = @selector(resetViewWithADXRecyclerView_ViewHolder:);
  methods[25].selector = @selector(onSelectedChangedWithADXRecyclerView_ViewHolder:withInt:);
  methods[26].selector = @selector(onMoveWithADXRecyclerView:withADXRecyclerView_ViewHolder:withADXRecyclerView_ViewHolder:);
  methods[27].selector = @selector(onSwipedWithADXRecyclerView_ViewHolder:withInt:);
  methods[28].selector = @selector(isLongPressDragEnabled);
  methods[29].selector = @selector(isDownPressDragEnabled);
  methods[30].selector = @selector(clearViewWithADXRecyclerView:withADXRecyclerView_ViewHolder:);
  methods[31].selector = @selector(onItemMoveWithInt:withInt:);
  methods[32].selector = @selector(getDragmode);
  methods[33].selector = @selector(setDragmodeWithNSString:);
  methods[34].selector = @selector(getMovementFlagsWithADXRecyclerView:withADXRecyclerView_ViewHolder:);
  methods[35].selector = @selector(getSwipeDirsWithADXRecyclerView:withADXRecyclerView_ViewHolder:);
  methods[36].selector = @selector(getDragDirsWithADXRecyclerView:withADXRecyclerView_ViewHolder:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "swipeListener_", "LASMyItemTouchHelper_MyCallback;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "onMoveListener_", "LASMyItemTouchHelper_MyCallback;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "onMovedListener_", "LASMyItemTouchHelper_MyCallback;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "onSelectedChangedListener_", "LASMyItemTouchHelper_MyCallback;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "deleteOnSwipe_", "Z", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "swipeSwapMode_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "adapter_", "LADXRecyclerView_Adapter;", .constantValue.asLong = 0, 0x12, -1, -1, 36, -1 },
    { "fromPosition_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "toPosition_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "currentTarget_", "LADXRecyclerView_ViewHolder;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "dragmode_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "dragStartMode_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "swapMode_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "selectHighlightAttributes_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "resetHighlightAttributes_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "setSelectHighlightAttributes", "LNSString;", "setDragStartMode", "setResetHighlightAttributes", "setSwapMode", "setSwipeSwapMode", "setDeleteOnSwipe", "Z", "setSwipeListener", "LASMyItemTouchHelper_MyCallback;", "setOnMoveListener", "setOnMovedListener", "setOnSelectedChangedListener", "LADXRecyclerView_Adapter;II", "(Landroidx/recyclerview/widget/RecyclerView$Adapter<*>;II)V", "chooseDropTarget", "LADXRecyclerView_ViewHolder;LJavaUtilList;II", "(Landroidx/recyclerview/widget/RecyclerView$ViewHolder;Ljava/util/List<Landroidx/recyclerview/widget/RecyclerView$ViewHolder;>;II)Landroidx/recyclerview/widget/RecyclerView$ViewHolder;", "selectView", "LADXRecyclerView_ViewHolder;", "applyStyle", "LADView;LNSString;", "resetView", "onSelectedChanged", "LADXRecyclerView_ViewHolder;I", "onMove", "LADXRecyclerView;LADXRecyclerView_ViewHolder;LADXRecyclerView_ViewHolder;", "onSwiped", "clearView", "LADXRecyclerView;LADXRecyclerView_ViewHolder;", "onItemMove", "II", "setDragmode", "getMovementFlags", "getSwipeDirs", "getDragDirs", "Landroidx/recyclerview/widget/RecyclerView$Adapter<*>;" };
  static const J2ObjcClassInfo _ASGenericTouchHelperSimpleCallback = { "GenericTouchHelperSimpleCallback", "com.ashera.recycleview", ptrTable, methods, fields, 7, 0x1, 37, 15, -1, -1, -1, -1, -1 };
  return &_ASGenericTouchHelperSimpleCallback;
}

@end

void ASGenericTouchHelperSimpleCallback_initWithADXRecyclerView_Adapter_withInt_withInt_(ASGenericTouchHelperSimpleCallback *self, ADXRecyclerView_Adapter *adapter, int32_t dragDirs, int32_t swipeDirs) {
  ADXItemTouchHelper_SimpleCallback_initWithInt_withInt_(self, dragDirs, swipeDirs);
  self->fromPosition_ = -1;
  self->toPosition_ = -1;
  self->adapter_ = adapter;
}

ASGenericTouchHelperSimpleCallback *new_ASGenericTouchHelperSimpleCallback_initWithADXRecyclerView_Adapter_withInt_withInt_(ADXRecyclerView_Adapter *adapter, int32_t dragDirs, int32_t swipeDirs) {
  J2OBJC_NEW_IMPL(ASGenericTouchHelperSimpleCallback, initWithADXRecyclerView_Adapter_withInt_withInt_, adapter, dragDirs, swipeDirs)
}

ASGenericTouchHelperSimpleCallback *create_ASGenericTouchHelperSimpleCallback_initWithADXRecyclerView_Adapter_withInt_withInt_(ADXRecyclerView_Adapter *adapter, int32_t dragDirs, int32_t swipeDirs) {
  J2OBJC_CREATE_IMPL(ASGenericTouchHelperSimpleCallback, initWithADXRecyclerView_Adapter_withInt_withInt_, adapter, dragDirs, swipeDirs)
}

void ASGenericTouchHelperSimpleCallback_applyStyleWithADView_withNSString_(ASGenericTouchHelperSimpleCallback *self, ADView *itemView, NSString *cssExpression) {
  id<ASIWidget> widget = [((id<ASILifeCycleDecorator>) nil_chk(((id<ASILifeCycleDecorator>) cast_check(itemView, ASILifeCycleDecorator_class_())))) getWidget];
  id<JavaUtilMap> attributes = ASModelExpressionParser_parseSimpleCssExpressionWithNSString_(cssExpression);
  for (NSString * __strong key in nil_chk([((id<JavaUtilMap>) nil_chk(attributes)) keySet])) {
    id value = [attributes getWithId:key];
    if ([((NSString *) nil_chk(key)) java_contains:@"#"]) {
      IOSObjectArray *keyAndId = [key java_split:@"#"];
      NSString *id_ = IOSObjectArray_Get(nil_chk(keyAndId), 0);
      key = IOSObjectArray_Get(keyAndId, 1);
      [((id<ASIWidget>) nil_chk([((id<ASIWidget>) nil_chk(widget)) findWidgetByIdWithNSString:JreStrcat("$$", @"@+id/", id_)])) setAttributeWithNSString:key withId:value withBoolean:false];
    }
    else {
      [((id<ASIWidget>) nil_chk(widget)) setAttributeWithNSString:key withId:value withBoolean:false];
    }
  }
}

void ASGenericTouchHelperSimpleCallback_resetViewWithADXRecyclerView_ViewHolder_(ASGenericTouchHelperSimpleCallback *self, ADXRecyclerView_ViewHolder *viewHolder) {
  ADView *itemView = ((ADXRecyclerView_ViewHolder *) nil_chk(viewHolder))->itemView_;
  if ([ASILifeCycleDecorator_class_() isInstance:itemView]) {
    if (self->resetHighlightAttributes_ != nil) {
      ASGenericTouchHelperSimpleCallback_applyStyleWithADView_withNSString_(self, itemView, self->resetHighlightAttributes_);
    }
  }
}

void ASGenericTouchHelperSimpleCallback_onItemMoveWithInt_withInt_(ASGenericTouchHelperSimpleCallback *self, int32_t fromPosition, int32_t toPosition) {
  if ([ASItemActionHandler_class_() isInstance:self->adapter_]) {
    [((id<ASItemActionHandler>) nil_chk(((id<ASItemActionHandler>) cast_check(self->adapter_, ASItemActionHandler_class_())))) onItemMoveWithInt:fromPosition withInt:toPosition withNSString:self->swapMode_];
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASGenericTouchHelperSimpleCallback)

J2OBJC_NAME_MAPPING(ASGenericTouchHelperSimpleCallback, "com.ashera.recycleview", "AS")
