//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSRecycleViewPlugin\src\main\java\com\ashera\recycleview\GenericTouchHelperSimpleCallback.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_GenericTouchHelperSimpleCallback")
#ifdef RESTRICT_GenericTouchHelperSimpleCallback
#define INCLUDE_ALL_GenericTouchHelperSimpleCallback 0
#else
#define INCLUDE_ALL_GenericTouchHelperSimpleCallback 1
#endif
#undef RESTRICT_GenericTouchHelperSimpleCallback

#if !defined (ASGenericTouchHelperSimpleCallback_) && (INCLUDE_ALL_GenericTouchHelperSimpleCallback || defined(INCLUDE_ASGenericTouchHelperSimpleCallback))
#define ASGenericTouchHelperSimpleCallback_

#define RESTRICT_ItemTouchHelper 1
#define INCLUDE_ADXItemTouchHelper_SimpleCallback 1
#include "ItemTouchHelper.h"

@class ADXRecyclerView;
@class ADXRecyclerView_Adapter;
@class ADXRecyclerView_ViewHolder;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASMyItemTouchHelper_MyCallback;
@protocol JavaUtilList;

@interface ASGenericTouchHelperSimpleCallback : ADXItemTouchHelper_SimpleCallback

#pragma mark Public

- (instancetype)initWithADXRecyclerView_Adapter:(ADXRecyclerView_Adapter *)adapter
                                        withInt:(int32_t)dragDirs
                                        withInt:(int32_t)swipeDirs;

- (ADXRecyclerView_ViewHolder *)chooseDropTargetWithADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)selected
                                                              withJavaUtilList:(id<JavaUtilList>)dropTargets
                                                                       withInt:(int32_t)curX
                                                                       withInt:(int32_t)curY;

- (void)clearViewWithADXRecyclerView:(ADXRecyclerView *)recyclerView
      withADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder;

- (int32_t)getDragDirsWithADXRecyclerView:(ADXRecyclerView *)recyclerView
           withADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder;

- (NSString *)getDragmode;

- (NSString *)getDragStartMode;

- (int32_t)getMovementFlagsWithADXRecyclerView:(ADXRecyclerView *)recyclerView
                withADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder;

- (id<ASMyItemTouchHelper_MyCallback>)getOnMovedListener;

- (id<ASMyItemTouchHelper_MyCallback>)getOnMoveListener;

- (id<ASMyItemTouchHelper_MyCallback>)getOnSelectedChangedListener;

- (NSString *)getResetHighlightAttributes;

- (NSString *)getSelectHighlightAttributes;

- (NSString *)getSwapMode;

- (int32_t)getSwipeDirsWithADXRecyclerView:(ADXRecyclerView *)recyclerView
            withADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder;

- (id<ASMyItemTouchHelper_MyCallback>)getSwipeListener;

- (NSString *)getSwipeSwapMode;

- (bool)isDeleteOnSwipe;

- (bool)isDownPressDragEnabled;

- (bool)isLongPressDragEnabled;

- (bool)onMoveWithADXRecyclerView:(ADXRecyclerView *)recyclerView
   withADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder
   withADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)target;

- (void)onMovedWithADXRecyclerView:(ADXRecyclerView *)recyclerView
    withADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder
                           withInt:(int32_t)fromPos
    withADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)target
                           withInt:(int32_t)toPos
                           withInt:(int32_t)x
                           withInt:(int32_t)y;

- (void)onSelectedChangedWithADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder
                                                withInt:(int32_t)actionState;

- (void)onSwipedWithADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder
                                       withInt:(int32_t)direction;

- (void)selectViewWithADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder;

- (void)setDeleteOnSwipeWithBoolean:(bool)deleteOnSwipe;

- (void)setDragmodeWithNSString:(NSString *)dragmode;

- (void)setDragStartModeWithNSString:(NSString *)dragStartMode;

- (void)setOnMovedListenerWithASMyItemTouchHelper_MyCallback:(id<ASMyItemTouchHelper_MyCallback>)onMovedListener;

- (void)setOnMoveListenerWithASMyItemTouchHelper_MyCallback:(id<ASMyItemTouchHelper_MyCallback>)onMoveListener;

- (void)setOnSelectedChangedListenerWithASMyItemTouchHelper_MyCallback:(id<ASMyItemTouchHelper_MyCallback>)onSelectedChangedListener;

- (void)setResetHighlightAttributesWithNSString:(NSString *)resetHighlightAttributes;

- (void)setSelectHighlightAttributesWithNSString:(NSString *)selectHighlightAttributes;

- (void)setSwapModeWithNSString:(NSString *)swapMode;

- (void)setSwipeListenerWithASMyItemTouchHelper_MyCallback:(id<ASMyItemTouchHelper_MyCallback>)swipeListener;

- (void)setSwipeSwapModeWithNSString:(NSString *)swipeSwapMode;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithInt:(int32_t)arg0
                    withInt:(int32_t)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASGenericTouchHelperSimpleCallback)

FOUNDATION_EXPORT void ASGenericTouchHelperSimpleCallback_initWithADXRecyclerView_Adapter_withInt_withInt_(ASGenericTouchHelperSimpleCallback *self, ADXRecyclerView_Adapter *adapter, int32_t dragDirs, int32_t swipeDirs);

FOUNDATION_EXPORT ASGenericTouchHelperSimpleCallback *new_ASGenericTouchHelperSimpleCallback_initWithADXRecyclerView_Adapter_withInt_withInt_(ADXRecyclerView_Adapter *adapter, int32_t dragDirs, int32_t swipeDirs) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASGenericTouchHelperSimpleCallback *create_ASGenericTouchHelperSimpleCallback_initWithADXRecyclerView_Adapter_withInt_withInt_(ADXRecyclerView_Adapter *adapter, int32_t dragDirs, int32_t swipeDirs);

J2OBJC_TYPE_LITERAL_HEADER(ASGenericTouchHelperSimpleCallback)

@compatibility_alias ComAsheraRecycleviewGenericTouchHelperSimpleCallback ASGenericTouchHelperSimpleCallback;


#endif

#pragma pop_macro("INCLUDE_ALL_GenericTouchHelperSimpleCallback")
