//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSRecycleViewPlugin\src\main\java\com\ashera\recycleview\ItemActionHandler.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "ItemActionHandler.h"
#include "J2ObjC_source.h"




#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface ASItemActionHandler : NSObject

@end

@implementation ASItemActionHandler

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 2, 3, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, 4, 5, -1, -1, -1, -1 },
    { NULL, "I", 0x401, 6, 5, -1, -1, -1, -1 },
    { NULL, "I", 0x401, 7, 5, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(onItemMoveWithInt:withInt:withNSString:);
  methods[1].selector = @selector(onItemRemoveWithInt:withNSString:);
  methods[2].selector = @selector(isDragEnabledWithADXRecyclerView_ViewHolder:);
  methods[3].selector = @selector(getSwipeDirsWithADXRecyclerView_ViewHolder:);
  methods[4].selector = @selector(getDragDirsWithADXRecyclerView_ViewHolder:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "onItemMove", "IILNSString;", "onItemRemove", "ILNSString;", "isDragEnabled", "LADXRecyclerView_ViewHolder;", "getSwipeDirs", "getDragDirs" };
  static const J2ObjcClassInfo _ASItemActionHandler = { "ItemActionHandler", "com.ashera.recycleview", ptrTable, methods, NULL, 7, 0x609, 5, 0, -1, -1, -1, -1, -1 };
  return &_ASItemActionHandler;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ASItemActionHandler)

J2OBJC_NAME_MAPPING(ASItemActionHandler, "com.ashera.recycleview", "AS")
