//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSRecycleViewPlugin\src\main\java\com\ashera\recycleview\ItemActionHandler.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ItemActionHandler")
#ifdef RESTRICT_ItemActionHandler
#define INCLUDE_ALL_ItemActionHandler 0
#else
#define INCLUDE_ALL_ItemActionHandler 1
#endif
#undef RESTRICT_ItemActionHandler

#if !defined (ASItemActionHandler_) && (INCLUDE_ALL_ItemActionHandler || defined(INCLUDE_ASItemActionHandler))
#define ASItemActionHandler_

@class ADXRecyclerView_ViewHolder;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;

@protocol ASItemActionHandler < JavaObject >

- (void)onItemMoveWithInt:(int32_t)fromPosition
                  withInt:(int32_t)toPosition
             withNSString:(NSString *)mode;

- (void)onItemRemoveWithInt:(int32_t)position
               withNSString:(NSString *)mode;

- (bool)isDragEnabledWithADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder;

- (int32_t)getSwipeDirsWithADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder;

- (int32_t)getDragDirsWithADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder;

@end

J2OBJC_EMPTY_STATIC_INIT(ASItemActionHandler)

J2OBJC_TYPE_LITERAL_HEADER(ASItemActionHandler)

#define ComAsheraRecycleviewItemActionHandler ASItemActionHandler


#endif

#pragma pop_macro("INCLUDE_ALL_ItemActionHandler")
