//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSRecycleViewPlugin\src\main\java\com\ashera\recycleview\MyItemTouchHelper.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "J2ObjC_source.h"
#include "MyItemTouchHelper.h"




#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface ASMyItemTouchHelper : NSObject

@end

@interface ASMyItemTouchHelper_MyCallback : NSObject

@end

@implementation ASMyItemTouchHelper

+ (const J2ObjcClassInfo *)__metadata {
  static const void *ptrTable[] = { "LASMyItemTouchHelper_MyCallback;" };
  static const J2ObjcClassInfo _ASMyItemTouchHelper = { "MyItemTouchHelper", "com.ashera.recycleview", ptrTable, NULL, NULL, 7, 0x609, 0, 0, -1, 0, -1, -1, -1 };
  return &_ASMyItemTouchHelper;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ASMyItemTouchHelper)

J2OBJC_NAME_MAPPING(ASMyItemTouchHelper, "com.ashera.recycleview", "AS")

@implementation ASMyItemTouchHelper_MyCallback

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, 2, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 6, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(onSwipedWithADXRecyclerView_ViewHolder:withInt:);
  methods[1].selector = @selector(onMoveWithADXRecyclerView:withADXRecyclerView_ViewHolder:withADXRecyclerView_ViewHolder:);
  methods[2].selector = @selector(onMovedWithADXRecyclerView:withInt:withInt:);
  methods[3].selector = @selector(onSelectedChangedWithADXRecyclerView_ViewHolder:withInt:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "onSwiped", "LADXRecyclerView_ViewHolder;I", "onMove", "LADXRecyclerView;LADXRecyclerView_ViewHolder;LADXRecyclerView_ViewHolder;", "onMoved", "LADXRecyclerView;II", "onSelectedChanged", "LASMyItemTouchHelper;" };
  static const J2ObjcClassInfo _ASMyItemTouchHelper_MyCallback = { "MyCallback", "com.ashera.recycleview", ptrTable, methods, NULL, 7, 0x609, 4, 0, 7, -1, -1, -1, -1 };
  return &_ASMyItemTouchHelper_MyCallback;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ASMyItemTouchHelper_MyCallback)
