//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSRecycleViewPlugin\src\main\java\com\ashera\recycleview\MyItemTouchHelper.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_MyItemTouchHelper")
#ifdef RESTRICT_MyItemTouchHelper
#define INCLUDE_ALL_MyItemTouchHelper 0
#else
#define INCLUDE_ALL_MyItemTouchHelper 1
#endif
#undef RESTRICT_MyItemTouchHelper

#if !defined (ASMyItemTouchHelper_) && (INCLUDE_ALL_MyItemTouchHelper || defined(INCLUDE_ASMyItemTouchHelper))
#define ASMyItemTouchHelper_

@protocol ASMyItemTouchHelper < JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(ASMyItemTouchHelper)

J2OBJC_TYPE_LITERAL_HEADER(ASMyItemTouchHelper)

#define ComAsheraRecycleviewMyItemTouchHelper ASMyItemTouchHelper


#endif

#if !defined (ASMyItemTouchHelper_MyCallback_) && (INCLUDE_ALL_MyItemTouchHelper || defined(INCLUDE_ASMyItemTouchHelper_MyCallback))
#define ASMyItemTouchHelper_MyCallback_

@class ADXRecyclerView;
@class ADXRecyclerView_ViewHolder;
@class JavaLangBoolean;
@class JavaLangInteger;

@protocol ASMyItemTouchHelper_MyCallback < JavaObject >

- (void)onSwipedWithADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder
                                       withInt:(int32_t)direction;

- (bool)onMoveWithADXRecyclerView:(ADXRecyclerView *)recyclerView
   withADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder
   withADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)target;

- (void)onMovedWithADXRecyclerView:(ADXRecyclerView *)recyclerView
    withADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder
                           withInt:(int32_t)fromPos
    withADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)target
                           withInt:(int32_t)toPos
                           withInt:(int32_t)x
                           withInt:(int32_t)y;

- (void)onSelectedChangedWithADXRecyclerView_ViewHolder:(ADXRecyclerView_ViewHolder *)viewHolder
                                                withInt:(int32_t)actionState;

@end

J2OBJC_EMPTY_STATIC_INIT(ASMyItemTouchHelper_MyCallback)

J2OBJC_TYPE_LITERAL_HEADER(ASMyItemTouchHelper_MyCallback)


#endif

#pragma pop_macro("INCLUDE_ALL_MyItemTouchHelper")
